/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CallToAction: React.FC = () => {
  return (
    <section id="cta" className="justify-center self-stretch pb-20 mt-16 w-full max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col max-md:gap-0">
        <div className="flex flex-col w-[16%] max-md:ml-0 max-md:w-full">
          <img
            loading="lazy"
            src="/gradient.svg"
            alt=""
            className="shrink-0 max-w-full aspect-[0.86] blur-[42px] w-[220px] max-md:mt-10"
          />
        </div>
        <div className="flex flex-col ml-5 w-[84%] max-md:ml-0 max-md:w-full">
          <div className="grow justify-center mt-20 rounded-3xl max-md:mt-10 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">
              <div className="flex flex-col w-[63%] max-md:ml-0 max-md:w-full">
                <div className="flex flex-col justify-end self-stretch my-auto font-bold max-md:mt-10 max-md:max-w-full">
                  <h2 className="text-5xl bg-clip-text bg-[linear-gradient(234deg,#AAD9D1_0%,#017373_125.68%)] leading-[58px] text-stone-200 max-md:max-w-full max-md:text-4xl max-md:leading-[54px]">
                    Откройте полный потенциал ИТ-аутсорсинга
                  </h2>
                  <p className="mt-6 text-base leading-6 text-zinc-400 max-md:max-w-full">
                    Готовы оптимизировать свои рабочие процессы и повысить продуктивность? Начните использовать наши услуги ИТ-аутсорсинга уже сегодня и ощутите преимущества профессиональной поддержки.
                  </p>
                  <button className="flex gap-4 self-start px-10 py-4 mt-8 text-lg leading-5 text-center rounded-lg bg-[linear-gradient(234deg,#AAD9D1_0%,#017373_125.68%)] text-zinc-950 max-md:px-5">
                    <span className="my-auto">Начать работу</span>
                    <img
                      loading="lazy"
                      src="/arrow_black.svg"
                      alt=""
                      className="shrink-0 w-8"
                    />
                  </button>
                </div>
              </div>
              <div className="flex flex-col ml-5 w-[37%] max-md:ml-0 max-md:w-full">
                <img
                  loading="lazy"
                  src="hero2.svg"
                  alt="Интерфейс SmartNotes"
                  className="w-full aspect-square max-md:mt-10"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default CallToAction;
