/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  const footerLinks = [
    {
      title: "Product",
      links: ["About", "Features", "Pricing", "Integrations", "FAQs"],
    },
    {
      title: "Company",
      links: ["Our Story", "Team", "Careers", "Press", "Contact Us"],
    },
    {
      title: "Resources",
      links: ["Blog", "Webinars", "Case Studies", "Templates", "Help Center"],
    },
    {
      title: "Legal",
      links: [
        "Terms of Service",
        "Privacy Policy",
        "Cookie Policy",
        "Acceptable Use",
        "Refund Policy",
      ],
    },
  ];

  const socialIcons = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/222bbcf3edc9eee6ec970e75eadd00f0f271e78617f6ba6e897dce647a11feeb?apiKey=4ba47913d9a146748073b7201a6fb4a1&",
      alt: "Facebook",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/b55542328a1aeb06df6c1e733c5f7452323a8c03ccefa1f39d36203ab9dea4ec?apiKey=4ba47913d9a146748073b7201a6fb4a1&",
      alt: "Twitter",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/1cd9b9e7d8f9df9cc592b45e71d0d5327fe1b38ad8a6d1a2dd9513613864f742?apiKey=4ba47913d9a146748073b7201a6fb4a1&",
      alt: "LinkedIn",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/56ad8d4aba45b8ef43c17e221cc8a7a54a5f96162c33d1a462f2ff7eba9ffb80?apiKey=4ba47913d9a146748073b7201a6fb4a1&",
      alt: "Instagram",
    },
  ];

  return (
    <footer className="flex flex-col self-stretch w-full border-t border-teal-600 border-solid bg-zinc-950 max-md:max-w-full">
      {/* <div className="flex justify-center items-center px-16 w-full max-md:px-5 max-md:max-w-full">
        <div className="w-full max-w-6xl max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col max-md:gap-0">
            <div className="flex flex-col w-[28%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow justify-between self-stretch max-md:mt-10">
                <div className="flex gap-2 justify-center pr-20 max-md:pr-5">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/f7502cbb2a413d3620b5a62b309850eab2095e4e56961c807b81ad5738be5a0b?apiKey=4ba47913d9a146748073b7201a6fb4a1&"
                    alt=""
                    className="shrink-0 aspect-square fill-[linear-gradient(234deg,#AAD9D1_0%,#017373_125.68%)] w-[38px]"
                  />
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/95cedaaf323161f199762e6b06d3f9bf92c8706a0499775bb430565ed9884751?apiKey=4ba47913d9a146748073b7201a6fb4a1&"
                    alt="SmartNotes"
                    className="shrink-0 my-auto max-w-full aspect-[7.69] fill-stone-200 w-[137px]"
                  />
                </div>
                <form className="flex gap-2.5 px-4 py-2 mt-20 text-sm leading-5 whitespace-nowrap rounded-lg border border-teal-600 border-solid bg-stone-200 text-zinc-800 max-md:mt-10">
                  <label htmlFor="footer-email" className="sr-only">
                    Email address
                  </label>
                  <input
                    type="email"
                    id="footer-email"
                    placeholder="email@smartnote.io"
                    className="flex-1 my-auto bg-transparent border-none"
                    aria-label="Email address"
                  />
                  <button type="submit" aria-label="Subscribe">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/eb4485b36382e408fecfbf5fadc2684410c790ef03477d3a9b8ac3616bbc0160?apiKey=4ba47913d9a146748073b7201a6fb4a1&"
                      alt=""
                      className="shrink-0 w-8 border border-teal-600 border-solid aspect-square stroke-[1px] stroke-teal-600"
                    />
                  </button>
                </form>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-[72%] max-md:ml-0 max-md:w-full">
              <div className="grow justify-between max-md:mt-10 max-md:max-w-full">
                <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                  {footerLinks.map((column, index) => (
                    <div
                      key={index}
                      className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full"
                    >
                      <div className="flex flex-col grow text-base leading-6 whitespace-nowrap max-md:mt-10">
                        <h3 className="text-lg font-bold text-stone-200">
                          {column.title}
                        </h3>
                        {column.links.map((link, linkIndex) => (
                          <a
                            key={linkIndex}
                            href="#"
                            className={`mt-${linkIndex === 0 ? "3.5" : "4"} ${
                              link === "Pricing"
                                ? "bg-clip-text bg-[linear-gradient(234deg,#AAD9D1_0%,#017373_125.68%)]"
                                : "text-zinc-400"
                            }`}
                          >
                            {link}
                          </a>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div> */}
      <div className="flex justify-center items-center px-16 py-2 w-full bg-teal-600 max-md:px-5 max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 justify-between w-full max-w-[1136px] max-md:flex-wrap max-md:max-w-full">
          <p className="my-auto text-sm leading-5 underline text-zinc-950">
            @2024 ShareX Все права защищены.{" "}
            {/* <a
              href="https://twitter.com/iamhervewabo"
              className="underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              @iamhervewabo
            </a> */}
          </p>
          {/* <div className="flex gap-2.5 py-2.5">
            {socialIcons.map((icon, index) => (
              <a
                key={index}
                href="#"
                className="flex justify-center items-center p-2.5 w-10 h-10 bg-teal-700 rounded-[58px]"
                aria-label={icon.alt}
              >
                <img
                  loading="lazy"
                  src={icon.src}
                  alt=""
                  className="w-5 aspect-square"
                />
              </a>
            ))}
          </div> */}
        </div>
      </div>
    </footer>
  );
};

export default Footer;
