/**
 * This code was generated by Builder.io.
 */
import React from "react";

const LogoStrip: React.FC = () => {
  const logos = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/b841dfff3ace547963624c2594b7438de29b3ce3c5529b8e0ec27ced2f2d1095?apiKey=4ba47913d9a146748073b7201a6fb4a1&",
      width: "71px",
      aspect: "4.35",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/203d84a4dfb50ac89b3b3b1f8b0aca037ea80c96e614bb037c9956264ed25f2a?apiKey=4ba47913d9a146748073b7201a6fb4a1&",
      width: "87px",
      aspect: "5.56",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/10b823336407c271047ac2467adc3f91ef3de81f9adb93bdb87d5b3d6b2374dd?apiKey=4ba47913d9a146748073b7201a6fb4a1&",
      width: "70px",
      aspect: "4.35",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/3921125e128b5c6c2d38ec4ff2d373c0fa700e6155a89a2e3437a15d2d782d3c?apiKey=4ba47913d9a146748073b7201a6fb4a1&",
      width: "87px",
      aspect: "5.56",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/1c9b174208ca84bcbf9e1c9d9b2a4608508d1ac1fcb386ed28379a5a3a8fb7be?apiKey=4ba47913d9a146748073b7201a6fb4a1&",
      width: "81px",
      aspect: "5",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/38e67beaa7abc422402d0affa68ac0a184b0790d5a5fc943a22a7caf2e2c0928?apiKey=4ba47913d9a146748073b7201a6fb4a1&",
      width: "87px",
      aspect: "5.56",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/b338a732a80b1f39bc5ebe0d28a8de427268d3c52d031e799fd9ed1f5d423306?apiKey=4ba47913d9a146748073b7201a6fb4a1&",
      width: "81px",
      aspect: "5",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/e47aa628189b661cb4869db1d39af3966fd3831c5eef1c871078d63e3dbff2d5?apiKey=4ba47913d9a146748073b7201a6fb4a1&",
      width: "87px",
      aspect: "5.56",
    },
  ];

  return (
    <div className="flex flex-wrap justify-center content-center items-center self-stretch px-16 py-6 w-full max-md:px-5 max-md:max-w-full">
      <div className="flex gap-5 justify-between w-full max-w-[1218px] max-md:flex-wrap max-md:max-w-full">
        {logos.map((logo, index) => (
          <img
            key={index}
            loading="lazy"
            src={logo.src}
            alt={`Partner logo ${index + 1}`}
            className={`shrink-0 aspect-[${logo.aspect}] w-[${logo.width}]`}
          />
        ))}
      </div>
    </div>
  );
};

export default LogoStrip;
