/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Hero from "./Hero";
import LogoStrip from "./LogoStrip";
import Testimonial from "./Testimonial";
import Features from "./Features";
import PricingPlans from "./PricingPlans";
import FAQ from "./FAQ";
import CallToAction from "./CallToAction";
import Footer from "./Footer";

const SmartNotes: React.FC = () => {
  return (
    <div className="flex flex-col items-center bg-zinc-950">
      <Header />
      <Hero />
      {/* <LogoStrip /> */}
      <Testimonial
        quote="Ваши ИТ-задачи теперь в надежных руках, и вы можете полностью сосредоточиться на развитии бизнеса."
        author="Нұрсұлтан Раушанбеков"
        company="ShareX"
      />
      <Features />
      <Testimonial
        quote="Реальная синхронизация и организация на базе ИИ сделали наш рабочий процесс более эффективным, чем когда-либо."
        author="Шерхан Сәрсен"
        company="ShareX"
      />
      {/* <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/be673c46f869808d9c211d328692287e539fc66a5ec2e386a43800f8dabb259c?apiKey=4ba47913d9a146748073b7201a6fb4a1&"
        alt=""
        className="self-stretch mt-16 w-full aspect-[1.85] max-md:mt-10 max-md:max-w-full"
      /> */}
      {/* <Testimonial
        quote="The real-time synchronization and AI-powered organization have made our workflow more efficient than ever."
        author="Sarah Johnson"
        company="TechSavvy Solutions"
      /> */}
      {/* <PricingPlans /> */}
      {/* <Testimonial
        quote="The real-time synchronization and AI-powered organization have made our workflow more efficient than ever."
        author="Sarah Johnson"
        company="TechSavvy Solutions"
      /> */}
      <FAQ />
      <Testimonial
        quote="Наши ИТ-задачи теперь в надежных руках благодаря профессиональному аутсорсингу, и мы можем полностью сосредоточиться на развитии бизнеса."
        author="Арман Сәрсембек"
        company="iRocket"
      />

      <CallToAction />
      <Footer />
    </div>
  );
};

export default SmartNotes;
